// <auto-generated />
using EFinheritance.Efdata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFinheritance.Migrations
{
    [DbContext(typeof(WebDbContext))]
    [Migration("20240117190720_Initials")]
    partial class Initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFinheritance.Models.User", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("UserRecord");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFinheritance.Models.Admin", b =>
                {
                    b.HasBaseType("EFinheritance.Models.User");

                    b.Property<string>("AdminRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("EFinheritance.Models.RegularUser", b =>
                {
                    b.HasBaseType("EFinheritance.Models.User");

                    b.Property<string>("UserLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("RegularUser");
                });
#pragma warning restore 612, 618
        }
    }
}
